### PR TITLE
feat(evm): EVMLA (E, I) pipelines

### PR DESCRIPTION
**Pull request by hedgar2017**
# What ❔

Fixes the EVMLA pipeline for EVM target.

## Why ❔

Some deploy code functions were unsupported.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Review by antonbaliasnikov — COMMENTED** [review]
By some reason licensing started to fail:
```
error[rejected]: failed to satisfy license requirements
  ┌─ registry+https://github.com/rust-lang/crates.io-index#icu_collections@1.5.0:4:12
  │
4 │ license = "Unicode-3.0"
  │            ^^^^^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: not explicitly allowed
```

**Comment by hedgar2017** [comment]
@antonbaliasnikov yeah, that seems to have been triggered by some external intervention.

**Comment by hedgar2017** [comment]
To be merged after https://github.com/matter-labs/era-compiler-vyper/pull/127 where `main` still depends on `structopt`.

**Review by antonbaliasnikov — APPROVED** [review]

**Comment by antonbaliasnikov** [comment]
@hedgar2017 , I've updated cargo.lock and restarted CI.

**Comment by hedgar2017** [comment]
@antonbaliasnikov it looks like the checks are still not mandatory here.
Could you please check if it's so in all repos?

**Pull request merged**
