### PR TITLE
chore: update contracts and tweak options for lazy stack implementation

### PR DESCRIPTION
**Pull request by vladimirradosavljevic**

### CODE REVIEW

**Comment by hedgar2017** [comment]
@vladimirradosavljevic let's merge?

**Comment by hedgar2017** [comment]
@vladimirradosavljevic sorry, overlooked the 2nd sentence.
Let's not close any PRs if we still plan to merge them, so they do not get lost.

**Comment by hedgar2017** [comment]
Hey @antonbaliasnikov, do you know why `cargo-udeps` might crash here?

**Comment by antonbaliasnikov** [comment]
> Hey @antonbaliasnikov, do you know why `cargo-udeps` might crash here?

It looks like `cargo-udeps` is broken with the latest release and cannot be built correctly with our current setup... maybe, they broke compatibility with older `cargo` versions. I'm checking and trying to fix.

**Pull request merged**
