### PR TITLE
feat: tests for remaining EVM opcodes

### PR DESCRIPTION
**Pull request by gianbelinche**
# What ❔

This PR adds the code necessary to perform the tests of the rest of the opcodes added on this [PR](https://github.com/matter-labs/era-compiler-tests/pull/29)

## Why ❔

The Before case for the tests was added because when you tried to write a test that needed to create a contract, since the Template and Full share the vm instance, they both created the same contract, so the decommiter failed since it already knew the hash, that's why the Before test was added, in order to run the contract creation in it before Template and Full, so that the gas comparisons were still correct (instead of creating the contract on Template and not in Full, since that way a specific opcode gas would not be tested)

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Comment by hedgar2017** [comment]
Please save the LOG tests somewhere.
I'm OOO today, but will help to handle them later.

**Comment by gianbelinche** [comment]
> Please save the LOG tests somewhere. I'm OOO today, but will help to handle them later.

Sure, i created a branch `log-tests` with them

**Comment by hedgar2017** [comment]
@gianbelinche merged!
Please change the submodule back, and I'll merge this one.

**Comment by gianbelinche** [comment]
> @gianbelinche merged! Please change the submodule back, and I'll merge this one.

Done!

**Pull request merged**
