### PR TITLE
Fix init code

### PR DESCRIPTION
**Pull request by gianbelinche**
# What ❔

This PR fixes a bug when running evm tests which bytecode is longer than `0xff`, the offset parameter on `CODECOPY` was not correct.

You can check the error running this test

```
{ 
    "system_mode": true,
    "is_evm_interpreter_benchmark": true,
    "group": "EVMInterpreter",
    "cases": [],
    "contracts": {
        "Proxy": "Proxy.sol:Proxy"
    },
    "evm_contracts": {
        "Benchmark": {
            "runtime_code" : "6080604052348015600e575f80fd5b5036601f19018060205f375a5f80835f805f355af191505a81035f52503d5f60203e8015603c573d6020015ff35b503d6020015ffdfea26469706673582212205f8680c59539ea20d3b628bfd10fddba7ae0dcb956d36ecbd427f0002cf5062164736f6c63430008190033"
        },

        "CREATE_Template": {  
            "runtime_code" : "7F6080604052348015600E575F80FD5B5060AF80601A5F395FF3FE6080604052345F527F8015600E575F80FD5B50600436106026575F3560E01C80636D4CE63C14602A576020527F5B5F80FD5B60306044565B604051603B91906062565B60405180910390F35B5F6040527F6007905090565B5F819050919050565B605C81604C565B82525050565B5F60206060527F8201905060735F8301846055565B9291505056FEA264697066735822122013576080527F3DB24498D07DF7D6344F02FA1CCF8E15038B10C382A6D71537A002AD4E73647360A0527F6F6C63430008190033000000000000000000000000000000000000000000000060C05260C95F5F"
        },
        "CREATE_Full": {
            "runtime_code" :"7F6080604052348015600E575F80FD5B5060AF80601A5F395FF3FE6080604052345F527F8015600E575F80FD5B50600436106026575F3560E01C80636D4CE63C14602A576020527F5B5F80FD5B60306044565B604051603B91906062565B60405180910390F35B5F6040527F6007905090565B5F819050919050565B605C81604C565B82525050565B5F60206060527F8201905060735F8301846055565B9291505056FEA264697066735822122013576080527F3DB24498D07DF7D6344F02FA1CCF8E15038B10C382A6D71537A002AD4E73647360A0527F6F6C63430008190033000000000000000000000000000000000000000000000060C05260C95F5FF0"
        },
}
```

## Checklist

- [X] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

### CODE REVIEW

**Review by hedgar2017 — APPROVED** [review]
Thank you!
I was just going to fix it today.

**Comment by hedgar2017** [comment]
Could you also add your CREATE tests to era-compiler-tests?

**Comment by gianbelinche** [comment]
> Could you also add your CREATE tests to era-compiler-tests?

Sure, I'm currently working on adding tests for all the remaining opcodes, once i finish it i will make a PR with all of them.

Here is the [Draft](https://github.com/matter-labs/era-compiler-tests/pull/29)

**Comment by hedgar2017** [comment]
> > Could you also add your CREATE tests to era-compiler-tests?
> 
> 
> 
> Sure, I'm currently working on adding tests for all the remaining opcodes, once i finish it i will make a PR with all of them.
> 
> 
> 
> Here is the [Draft](https://github.com/matter-labs/era-compiler-tests/pull/29)

Thank you!
Could you point the `tests` submodule to your branch and push, so we can run the CI?

**Comment by gianbelinche** [comment]
@hedgar2017  I already added a [PR](https://github.com/matter-labs/era-compiler-tests/pull/29) for the rest of the tests, since that one needed more changes in this repo, I created a new [PR](https://github.com/matter-labs/era-compiler-tester/pull/25) containing all the new changes, since I based it from this branch, it already has this changes, so we can close this and focus on those two

**Comment by hedgar2017** [comment]
Sure, thanks!

**Pull request closed without merging**
